# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentsReceipt',
            fields=[
                ('token', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
                ('payd', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserCredits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('credit_amt', models.IntegerField(default=0)),
            ],
        ),
    ]
